### ISSUE TITLE
Need a Reset Button

### ISSUE THREAD

**Issue by daljeeet** [Amin-Partovi/react-speakup#2]
there are two functions startListening and stopListening. How about resetting the transcript? 
need a function to reset the transcripted text to the initial value.

**Comment by Amin-Partovi** [comment]
Thank you for your feedback and sorry for the late response. I appreciate any contribution. 

I think it can be implemented through one of these two scenarios:

adding reset() handler to remove the transcript.
adding pauseListening() and resumeListening() handlers and clean the transcript on startListening().

**Comment by doncarlo5** [comment]
Hey, Did you implement the reset function ?

**Comment by Amin-Partovi** [comment]
> Hey, Did you implement the reset function ?

Hi
No, I didn't. I'll implement it in coming days and let you know

**Comment by Amin-Partovi** [comment]
now, reset functionality is added to the useVoiceToText hook

**Comment by Amin-Partovi** [comment]
now, reset functionality is added to the useVoiceToText hook
